# application-dev.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.embedding.api-key=${spring.ai.google.genai.api-key}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

ai.loganalyzer.max-snippets=10
ai.loganalyzer.cache-ttl-hours=24h
ai.loganalyzer.parser-engine=javaparser
ai.loganalyzer.vector-store=pgvector

management.metrics.tags.environment=dev