spring.application.name=ailoganlzr
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9090
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.index-type=NONE

# Hybrid SDK configuration
ai.loganalyzer.client.server-url=http://localhost:9090
ai.loganalyzer.client.connect-timeout=5s
ai.loganalyzer.client.read-timeout=30s